### PR TITLE
Andrey branch

### PR DESCRIPTION
**Pull request by AndreyMich**
-added students.html
-added students.css

### CODE REVIEW

**Comment by davidmeirlevy** [comment]
make it simpler please.

**Comment by davidmeirlevy** [comment]
also, the PR title should say what it is.

**Comment by AndreyMich** [comment]
@davidmeirlevy 
I`ve changed the entire structure after your comments.
Please approve PR

**Comment by davidmeirlevy** [comment]
Don't mix working on your own CV to the students page.
Those should be 2 different PRs.

**Comment by AndreyMich** [comment]
@davidmeirlevy 
deleted redundant folder from this PR

**Pull request closed without merging**
